### ISSUE TITLE
Problems with currency on Mac OS

### ISSUE THREAD

**Issue by ghost** [mrooney/wxbanker#9]
Even after setup correct locale (as shown below) the method getlocale on currencies.py cant get the correct locale:

My locales:

**flamarion@arvore:~$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=**

Workaround:

--- Softwares/wxbanker/wxbanker/currencies.py	2017-02-01 08:31:11.000000000 +0100
+++ /usr/local/lib/python2.7/site-packages/wxbanker/currencies.py	2017-02-01 09:40:14.000000000 +0100
@@ -106,8 +106,8 @@
             ##locale._override_localeconv = None
             locale.localeconv = localeConvBackup

-        if not isinstance(s, unicode):
-            s = unicode(s, locale.getlocale()[1])
+        #if not isinstance(s, unicode):
+        #    s = unicode(s, locale.getlocale()[1])

         if withNick:
             s = self.GetCurrencyNick() + " " + s

I know nothing about the programming, but I just commented the get.locale on currencies.py and then the wxbanker worked very nice on Mac Os.

Below my mac setup:

macOS Sierra - Version 10.12.2
python --version
Python 2.7.13

**Comment by mrooney** [comment]
Thanks for the report and work-around! When it doesn't work, what happens? Does it crash, or simply display currencies in an unexpected way? Could you provide the terminal output if it crashes, or example of incorrect currency formatting? Thanks :)

**Comment by ghost** [comment]
Hi.... I reproduced the behavior step by step from scratch.

I deleted and cloned it again the repo, and installed the requirements

flamarion@arvore:~/Softwares/wxbanker$ pip install -r pip_requirements.txt
Collecting BeautifulSoup (from -r pip_requirements.txt (line 1))
  Downloading BeautifulSoup-3.2.1.tar.gz
Requirement already satisfied: keyring in /usr/local/lib/python2.7/site-packages (from -r pip_requirements.txt (line 2))
Collecting numpy (from -r pip_requirements.txt (line 3))
  Downloading numpy-1.12.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 232kB/s
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/site-packages (from -r pip_requirements.txt (line 4))
Collecting pyxdg (from -r pip_requirements.txt (line 5))
  Downloading pyxdg-0.25.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 3.8MB/s
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from -r pip_requirements.txt (line 6))
Collecting simplejson (from -r pip_requirements.txt (line 7))
  Downloading simplejson-3.10.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 2.9MB/s
Requirement already satisfied: xmltodict in /usr/local/lib/python2.7/site-packages (from -r pip_requirements.txt (line 8))
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from python-dateutil->-r pip_requirements.txt (line 4))
Building wheels for collected packages: BeautifulSoup, pyxdg, simplejson
  Running setup.py bdist_wheel for BeautifulSoup ... done
  Stored in directory: /Volumes/HD2/flamarion/Library/Caches/pip/wheels/5e/be/6d/ed01d5d434a821557b674c9da976f60b1b93d9009447eb9d16
  Running setup.py bdist_wheel for pyxdg ... done
  Stored in directory: /Volumes/HD2/flamarion/Library/Caches/pip/wheels/b5/a7/ef/3042e8873105107c61e1ebeae8ac4d0cff935339d8e228b73c
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /Volumes/HD2/flamarion/Library/Caches/pip/wheels/43/c5/ef/edcebbb19becffd2ba75bf219afdbb4ca85198b2d909f1b31b
Successfully built BeautifulSoup pyxdg simplejson
Installing collected packages: BeautifulSoup, numpy, pyxdg, simplejson
Successfully installed BeautifulSoup-3.2.1 numpy-1.12.0 pyxdg-0.25 simplejson-3.10.0

After clone it, this was my locale setup:

flamarion@arvore:~/Softwares/wxbanker$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

And with this locale the software produce this output (as expected I think so)

flamarion@arvore:~/Softwares/wxbanker$ python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from wxbanker.main import main
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/main.py", line 37, in <module>
    from wxbanker.menubar import BankMenuBar
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/menubar.py", line 26, in <module>
    from wxbanker.currencies import CurrencyStrings
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/currencies.py", line 570, in <module>
    CurrencyStrings = ["%s: %s" % (c().LOCALECONV['int_curr_symbol'].strip(), c().float2str(1)) for c in CurrencyList]
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/currencies.py", line 104, in float2str
    s = locale.currency(val, grouping=True)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 266, in currency
    raise ValueError("Currency formatting is not possible using "
ValueError: Currency formatting is not possible using the 'C' locale.

Then, I adjusted all locales to avoid the first behavior.

flamarion@arvore:~/Softwares/wxbanker$ export LC_ALL="en_US.UTF-8"
flamarion@arvore:~/Softwares/wxbanker$ locale
LANG=
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
flamarion@arvore:~/Softwares/wxbanker$ export LANG=en_US.UTF-8

Everything seem to be fine now, see

flamarion@arvore:~/Softwares/wxbanker$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

But, when I tried to run the software the "error" was changed as shown below:

flamarion@arvore:~/Softwares/wxbanker$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    main()
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/main.py", line 249, in main
    app = init()
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/main.py", line 236, in init
    frame = BankerFrame(bankController, welcome)
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/main.py", line 143, in __init__
    self.Panel = BankerPanel(self, bankController)
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/main.py", line 48, in __init__
    self.mainPanel = managetab.MainPanel(self, bankController)
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/managetab.py", line 41, in __init__
    self.accountCtrl = accountCtrl = accountlistctrl.AccountListCtrl(leftPanel, bankController)
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/accountlistctrl.py", line 84, in __init__
    self.totalText = wx.StaticText(self.childPanel, label=self.Model.float2str(0))
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/bankobjects/bankmodel.py", line 176, in float2str
    return currency.float2str(*args, **kwargs)
  File "/Volumes/HD2/flamarion/Softwares/wxbanker/wxbanker/currencies.py", line 110, in float2str
    s = unicode(s, locale.getlocale()[1])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Well, I think that this information help in some way
